# Generated by Django 3.1.5 on 2021-03-29 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuberecords', '0002_comment_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record_request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spent_time', models.FloatField()),
                ('text', models.TextField(max_length=4096)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creation timestamp')),
                ('document', models.FileField(upload_to='')),
            ],
        ),
    ]
